DROP TABLE IF EXISTS `courses`;

CREATE TABLE courses (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,       -- 自動採番 PK
    name VARCHAR(50) NOT NULL COMMENT 'コース名（ベーシック、マスター）',
    created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP -- 作成日時
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='受講コース';